---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/dagger version
    register: dagger_test_output
  - name: dagger version
    debug:
      msg: '{{ dagger_test_output.stdout }}'
